// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4ar_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ar_drift_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dlm_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dlm_int_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dlm_slope_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ma1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4marss_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4regression_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4regression_cor_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4rw_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4rw_drift_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ss_ar_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ss_ar_drift_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ss_ar_mean_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ss_rw_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ss_rw_drift_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4ar_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ar_mod, 0},
    {"_rcpp_module_boot_stan_fit4ar_drift_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ar_drift_mod, 0},
    {"_rcpp_module_boot_stan_fit4dlm_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dlm_mod, 0},
    {"_rcpp_module_boot_stan_fit4dlm_int_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dlm_int_mod, 0},
    {"_rcpp_module_boot_stan_fit4dlm_slope_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dlm_slope_mod, 0},
    {"_rcpp_module_boot_stan_fit4ma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ma_mod, 0},
    {"_rcpp_module_boot_stan_fit4ma1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ma1_mod, 0},
    {"_rcpp_module_boot_stan_fit4marss_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4marss_mod, 0},
    {"_rcpp_module_boot_stan_fit4regression_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4regression_mod, 0},
    {"_rcpp_module_boot_stan_fit4regression_cor_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4regression_cor_mod, 0},
    {"_rcpp_module_boot_stan_fit4rw_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rw_mod, 0},
    {"_rcpp_module_boot_stan_fit4rw_drift_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4rw_drift_mod, 0},
    {"_rcpp_module_boot_stan_fit4ss_ar_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ss_ar_mod, 0},
    {"_rcpp_module_boot_stan_fit4ss_ar_drift_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ss_ar_drift_mod, 0},
    {"_rcpp_module_boot_stan_fit4ss_ar_mean_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ss_ar_mean_mod, 0},
    {"_rcpp_module_boot_stan_fit4ss_rw_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ss_rw_mod, 0},
    {"_rcpp_module_boot_stan_fit4ss_rw_drift_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ss_rw_drift_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_atsar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
